### ISSUE TITLE
license_compliance.md excludes "Gradle files" but rationale not sound

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-release#131]
In []() the exclusion table allows for "Gradle files" not having ASF headers; however, the rationale is simple "not much IP" which is not sound logic since we enforce license in Bash and make files whose files have an equal amount of functional logic. 

We wither need to explain better or enforce ASF license on gradle files where possible, that is for example on (gradlew.bat, build, gradle and gradlew):
- https://github.com/apache/incubator-openwhisk/blob/master/gradlew.bat
- https://github.com/apache/incubator-openwhisk/blob/master/gradlew
-https://github.com/apache/incubator-openwhisk/blob/master/build.gradle

Note that ASF license scanning (scancode may need to be updated if we decide to add.

**Comment by mrutkows** [comment]
and "settings.gradle" as well.

**Comment by daisy-ycguo** [comment]
and the folder "gradle" including:
- gradle/docker.gradle
- gradle/wrapper/gradle-wrapper.properties

My option is to add headers to `build.gradle` and `settings.gradle`, and ignore other gradle files, because
- gradlew.bat and gradlew are similar in all repositories. There is not many differences among them.
- gradle/docker.gradle are similar.
- gradle/wrapper/gradle-wrapper.properties is property file

@houshengbo please comments. Thanks.

**Comment by houshengbo** [comment]
I lean on to not add license header to gradlew.bat and gradlew, because they are generated br gradle wrapper and may vary in different versions of gradle wrapper. They are not what we developed, but generated.

For build.gradle and settings.gradle, we can add license headers.

**Comment by mrutkows** [comment]
Agree to close this as long as we add license to *.gradle config files.
